# Generated by Django 6.0.1 on 2026-02-08 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateField(default=datetime.date(2026, 2, 8)),
        ),
    ]
