# Generated by Django 6.0.1 on 2026-02-11 23:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_lesson_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateField(default=datetime.date(2026, 2, 12)),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.grade'),
        ),
    ]
