# Generated by Django 6.0.1 on 2026-02-12 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_file_file_path_alter_lesson_lesson_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.grade')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.lesson')),
            ],
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.homeworkgrade'),
        ),
    ]
