# Generated by Django 6.0.1 on 2026-02-12 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_homeworkgrade_alter_studenthomework_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.grade'),
        ),
    ]
