# Generated by Django 6.0.1 on 2026-02-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_studenthomework_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_homework',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HomeworkGrade',
        ),
    ]
