# Generated by Django 6.0.1 on 2026-02-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_grade_is_homework_delete_homeworkgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
