# Generated by Django 6.0.1 on 2026-02-13 18:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_schoolclass_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.grade'),
        ),
    ]
