# Generated by Django 6.0.1 on 2026-02-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='user_id',
            new_name='parent',
        ),
    ]
